name: deeplinker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  auto_route: ^9.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
